x = int (input("Enter 1st Number : "))
y= int (input("Enter 2st Number : ")) 
z=x+y 
print("Addition  = ",x+y)
print("Multipication = ",x*y)
print("Subtraction = ",x-y)
print("Divison = ",x/y)
print("Modulus = ",x%y)
print("Exponent = ",x**y)